// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAw6MR9jwtkLc4mkKugRKQwx9RCK_0r6ws',
    appId: '1:190066918484:web:7a56150217b8de99ab99c1',
    messagingSenderId: '190066918484',
    projectId: 'odoo-combat-finals',
    authDomain: 'odoo-combat-finals.firebaseapp.com',
    storageBucket: 'odoo-combat-finals.appspot.com',
    measurementId: 'G-J76TTSTFX6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIgmV-dGt3HS4ZZZqDBtJe4ZFdQ4bIF_8',
    appId: '1:190066918484:android:c771387857d4ced4ab99c1',
    messagingSenderId: '190066918484',
    projectId: 'odoo-combat-finals',
    storageBucket: 'odoo-combat-finals.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL-3Us3nluMfzSq2hT59bYpDx54vV_Yk0',
    appId: '1:190066918484:ios:d3cc578214ed8582ab99c1',
    messagingSenderId: '190066918484',
    projectId: 'odoo-combat-finals',
    storageBucket: 'odoo-combat-finals.appspot.com',
    iosBundleId: 'com.example.odooCombat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAL-3Us3nluMfzSq2hT59bYpDx54vV_Yk0',
    appId: '1:190066918484:ios:d3cc578214ed8582ab99c1',
    messagingSenderId: '190066918484',
    projectId: 'odoo-combat-finals',
    storageBucket: 'odoo-combat-finals.appspot.com',
    iosBundleId: 'com.example.odooCombat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAw6MR9jwtkLc4mkKugRKQwx9RCK_0r6ws',
    appId: '1:190066918484:web:464ddfd65b6750e5ab99c1',
    messagingSenderId: '190066918484',
    projectId: 'odoo-combat-finals',
    authDomain: 'odoo-combat-finals.firebaseapp.com',
    storageBucket: 'odoo-combat-finals.appspot.com',
    measurementId: 'G-35J3YJG48P',
  );
}
